#!/bin/sh

# This script is used to build the Antora-based
# documentation for Boost libraries and for the
# versioned site documentation such as the
# User's Guide.
#

if [ $# -eq 0 ]; then
    echo "Usage: $0 { branch | version | 'all' }..."
    echo
    echo "    branch : 'develop' | 'master' | 'release'"
    echo "    version: [0-9]+ '.' [0-9]+ '.' [0-9]+"
    echo
    echo "    'all' rebuilds develop, master, and every version"
    echo
    echo "Examples:"
    echo
    echo "    $0 develop master      # build develop and master"
    echo "    $0 1.83.0              # build tagged version boost-1.83.0"
    exit 2
fi

while test $# -gt 0
do
    if [ "$1" = "develop" ] || [ "$1" = "master" ]; then
        npx antora --fetch \
            --attribute boost_version=$1 \
            --attribute boost_ui_branch=$1 \
            --attribute boost_dir_prefix=$1/lib \
            libs.playbook.yml

    elif [ "$1" = "release" ]; then
        npx antora --fetch \
            --attribute boost_version=master \
            --attribute boost_ui_branch=master \
            --attribute boost_layout=release \
            --attribute boost_dir_prefix=doc/html \
            libs.playbook.yml

    elif [[ "$1" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
        npx antora --fetch \
            --attribute boost_version=$1 \
            --attribute boost_ui_branch=master \
            --attribute boost_dir_prefix=$1/lib \
            libs.playbook.yml

    elif [ "$1" = "all" ]; then
        echo "build all";
    else
        echo "invalid argument: '$1'"
    fi
    shift
done
