# This configures Antora for building library docs
#
# website link structure:
#
# boost.org/libs/{name}                         redirect to versioned docs
# boost.org/{version}/libs/{name}               versioned Antora lib docs
# boost.org/{version}/libs/user-guide           User Guide (VFALCO move to doc?)
# boost.org/doc/libs/{old-version}/libs/{name}  redirect to versioned legacy lib docs
#
# /libs/{name}                          Redirect to /{version}/lib/{name}
# /{version}/lib/{name}                 library docs
# /{version}/lib/user-guide             User Guide
# /{version}/doc/contributor-guide      Contributor Guide (master, develop only)
# /{version}/doc/boost-formal-review    Boost Formal Review (master, develop only)
#
# /doc/libs/{old-version}/libs/{name}   redirect to versioned legacy lib docs
#
# name:         library-name
# version:      "master" | "develop" | {semantic-version}
# old-version:  DIGIT+ '_' DIGIT+ '_' DIGIT+
#

asciidoc:
  attributes:
    boost_version: develop
    boost_ui_branch: develop
    boost_dir_prefix: develop/lib
    boost_layout: default

site:
  url: https://antora.cppalliance.org/${boost_version}/libs
  title: Boost Libraries Documentation
  start_page: user-guide::index.adoc
  robots: allow

antora:
  extensions:
    - require: ./boost.js

content:
  sources:
  - url: https://github.com/vinniefalco/user-guide
    start_path: antora
  - url: https://github.com/vinniefalco/mp11
    start_path: antora
  - url: https://github.com/vinniefalco/predef
    start_path: antora
  - url: https://github.com/vinniefalco/qvm
    start_path: antora
  - url: https://github.com/vinniefalco/unordered
    start_path: antora

ui:
  bundle:
    url: https://github.com/cppalliance/antora-ui/releases/download/ui-${boost_ui_branch}/ui-bundle.zip
    snapshot: true
  default_layout: ${boost_layout}

output:
  dir: ./build/${boost_dir_prefix}
