# This configures Antora for building library docs
#
# website link structure:
#
# boost.org/libs/{name} redirect to versioned docs
# boost.org/{version}/libs/{name} versioned Antora lib docs
# boost.org/{version}/doc/user-manual Antora user manual (per-release)
# boost.org/doc/contributor-manual  Antora contributor manual
# boost.org/doc/libs/{old-version}/libs/{name}  redirect to versioned legacy lib docs
#
# {version} uses dots: 1.82.0
# {old-version} uses underscores: 1_82_0
#

asciidoc:
  attributes:
    boost_version: master
    boost_ui_branch: master
    boost_doc_prefix: https://github.com/cppalliance
    boost_lib_prefix: https://github.com/vinniefalco
    boost_ui_prefix: https://github.com/cppalliance

    boost_dir_prefix: master

site:
  url: https://antora.cppalliance.org/${boost_version}/libs
  title: Boost Libraries Documentation
#  start_page: contributor-manual::index.adoc

antora:
  extensions:
    - require: ./boost.js

content:
  sources:
  - url: ${boost_doc_prefix}/user-manual
    start_path: antora
  - url: ${boost_doc_prefix}/contributor-manual
    start_path: antora
  - url: ${boost_lib_prefix}/mp11
    start_path: antora
  - url: ${boost_lib_prefix}/predef
    start_path: antora
  - url: ${boost_lib_prefix}/unordered
    start_path: antora
  - url: ${boost_lib_prefix}/qvm
    start_path: antora

ui:
  bundle:
    url: ${boost_ui_prefix}/antora-ui/releases/download/ui-${boost_ui_branch}/ui-bundle.zip
    snapshot: true

output:
  dir: ./build/${boost_dir_prefix}
