= Documentation
:idprefix:
:idseparator: -
:leveloffset: +0

This explains how the docs work.

## Antora demo  

https://antora.cppalliance.org  

https://master.antora.cpp.al (same as main site)  
https://develop.antora.cpp.al  

## Instructions  

The workflow may change in the future.

For the moment, the contents of build/site/ are being publish as-is to https://antora.cppalliance.org  

That means it's the developers responsibility to update playbooks, build files, and check in all files.  

- Modify antora-playbook.yml
- Run `npx antora --fetch antora-playbook.yml` and similar antora commands which builds the docs. The output automatically goes in build/site/
- Check into git  

The first set of docs were generated by following the instructions at https://docs.antora.org/antora/latest/install-and-run-quickstart/  

The version of node used:  

```
$ nvm install --lts
Installing latest LTS version.
Downloading and installing node v18.15.0...

$ node --version
v18.15.0
```

To work locally, i.e. in "author mode" using the local filesystem:
* Make a copy of playbook.yml named local.playbook.yml
* Change the URL for one or more content sources to point to the boost superproject
```
- url: C:/Users/vinnie/src/boost
```
* Change the start path to point to the submodule's antora directory:
```
  start_path: libs/mp11/antora
```

Alternatively if the library is not a submodule but a repo root, point to that
instead:
```
- url: C:/Users/vinnie/src/boost/libs/proposed-lib
  start_path: antora
```

## Instructions  

The workflow may change in the future.

For the moment, the contents of build/site/ are being publish as-is to https://antora.cppalliance.org  

The Asciidoc attribute "branch" is used to select the branch to be built.
It can be "master", "develop", or a boost release tag such as "boost-1.82.0".

There are two playbooks:

libs.yml        Builds per-release documentation such as libs and the user manual
website.yml     Builds release-independent website documentation such as the contributor manual

Build website first then libs. Set the branch from the CLI:

To build the master branch run antora as usual without attributes.

To build the develop branch for the website:
```
antora --fetch --attribute branch=master site.yml
antora --fetch --attribute branch=master libs.yml
```

To build the library documentation for just a release:

```
antora --fetch --attribute branch=boost-1.82.0 libs.yml
```

The master/develop branches of the website are designed to be
deployed to different domains, thus the branch does not appear
in its URLs.

The master/develop branches of the library documentation is
designed to co-exist alongside the per-release documentation
and thus the branch name (or release version) does appear
in its URLs.

When building a release the release layout is used which
omits the header, Google analytics, and Edit this Page.
