#!/bin/sh

# This script is used to build the site
# documentation which is not tagged per release.
#

if [ $# -eq 0 ]; then
    echo "Usage: $0 { 'develop' | 'master' }..."
    echo
    echo "Examples:"
    echo
    echo "    $0 develop        # build develop"
    echo "    $0 master         # build master"
    exit 2
fi

while test $# -gt 0
do
    if [ "$1" = "develop" ]; then
        npx antora --fetch \
            --attribute boost_version=$1 \
            --attribute boost_site_prefix=develop/ \
            site.playbook.yml

    elif [ "$1" = "master" ]; then
        npx antora --fetch \
            --attribute boost_version=$1 \
            --attribute boost_site_prefix= \
            site.playbook.yml

    else
        echo "invalid argument: '$1'"
    fi
    shift
done
