# This configures Antora for building site documentation

site:
  title: Site Documentation
  url: https://antora.cppalliance.org
  start_page: contributor-manual::index.adoc
antora:
  extensions:
    - require: ./branch-attribute.js
asciidoc:
  attributes:
    branch: master
content:
  sources:
  - url: https://github.com/cppalliance/contributor-manual
    start_path: antora
ui:
  bundle:
    #url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    url: https://github.com/cppalliance/antora-ui/releases/download/first/ui-${branch}.zip
    snapshot: true
output:
  dir: ./build/doc

