# This configures Antora for building site docs
#
# website link structure:
#
# /libs/{name}                          Redirect to /{version}/lib/{name}
# /{version}/lib/{name}                 library docs
# /{version}/lib/user-guide             User Guide
# /doc/contributor-guide
# /doc/boost-formal-review
# /develop/doc/contributor-guide
# /develop/doc/boost-formal-review
#
# /doc/libs/{old-version}/libs/{name}   redirect to versioned legacy lib docs
#
# name:         library-name
# version:      "master" | "develop" | {semantic-version}
# old-version:  DIGIT+ '_' DIGIT+ '_' DIGIT+
#

asciidoc:
  attributes:
    page-boost-branch: develop

site:
  url: https://antora.cppalliance.org/${page-boost-branch}/doc
  title: Guides
  start_page: contributor-guide::index.adoc

antora:
  extensions:
    - require: ./boost.js

content:
  sources:
  - url: https://github.com/cppalliance/site-docs
    start_path: user-guide
  - url: https://github.com/cppalliance/site-docs
    start_path: formal-reviews
  - url: https://github.com/cppalliance/site-docs
    start_path: release-process
    
  #---
  # distributed component version
  - url: https://github.com/cppalliance/site-docs
    start_path: contributor-guide
  - url: https://github.com/cppalliance/antora
    start_path: antora
  #---

ui:
  bundle:
    url: https://github.com/cppalliance/antora-ui/releases/download/ui-${page-boost-branch}/ui-bundle.zip
    snapshot: true

output:
  dir: ./build/${page-boost-branch}/doc
