name: Publish Antora
on:
  push:
    branches:
      - master
      - develop

concurrency:
  group: ${{format('{0}:{1}', github.repository, github.ref)}}
  cancel-in-progress: true

jobs:
  build:
    name: Publish Antora Docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        uses: ./.github/actions/antora_publish
        with:
          playbook: playbook.yml
          artifact: antora
          options: --fetch --attribute "branch=${{ (startsWith(github.ref, 'refs/heads/develop') && 'develop') || 'master' }}"
