name: Publish Antora
on: [push, pull_request]

concurrency:
  group: ${{format('{0}:{1}', github.repository, github.ref)}}
  cancel-in-progress: true


jobs:
  build:
    name: Publish Antora Docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Publish Libs
        uses: ./.github/actions/antora_publish
        with:
          playbook: libs.yml
          artifact: libs
          options: --fetch --attribute ${{ (startsWith(github.ref, 'refs/heads/develop') && 'develop') || 'master' }}

      - name: Publish Site
        uses: ./.github/actions/antora_publish
        with:
          playbook: site.yml
          artifact: site
          options: --fetch --attribute ${{ (startsWith(github.ref, 'refs/heads/develop') && 'develop') || 'master' }}
